### ISSUE TITLE
Need to add socket.js version control

### ISSUE THREAD

**Issue by zhayes** [lahsivjar/react-stomp#33] opened 2018-01-04 10:58 UTC
![image](https://user-images.githubusercontent.com/17758062/34560553-1adb9b30-f181-11e7-8f94-57472769271d.png)

**Comment by lahsivjar** [comment] 2018-01-04 11:36
@zhayes Please share more information to reproduce the issue

**Comment by lahsivjar** [comment] 2018-01-04 11:42
@zhayes Are you using `webpack-dev-server`. It maybe related with this issue https://github.com/webpack/webpack-dev-server/issues/474

**Comment by zhayes** [comment] 2018-01-04 11:48
@lahsivjar  yeah! i am using webpack-dev-server . So,  can't i use it to test on development staging?

**Comment by lahsivjar** [comment] 2018-01-04 11:52
@zhayes According to https://github.com/webpack/webpack-dev-server/issues/474 it seems to be an issue of the `webpack-dev-server` dependency management and should be fixed in this PR: https://github.com/webpack/webpack-dev-server/pull/493

Maybe you can try to update the version of `webpack-dev-server` and check if the issue persists

**Comment by lahsivjar** [comment] 2018-01-05 09:39
@zhayes Was the problem resolved?

**Comment by lahsivjar** [comment] 2018-01-05 16:43
Closing this ticket because of lack of evidence suggesting a problem with this project. Feel free to reopen if the situation changes

**Closed by lahsivjar** 2018-01-05 16:43 UTC
Labels: WaitingForReply

**Comment by zhayes** [comment] 2018-01-05 17:30
My partner tuned up the background interface and solved it for the time being.I don't update webpack-dev-server.

Vishal Raj <notifications@github.com> 于 2018年1月5日 下午5:39写道：


@zhayes<https://github.com/zhayes> Was the problem resolved?

―
